[package]
name = "piston_ant"
version = "1.0.0"
authors = ["Josef Kucha≈ô <email@josefkuchar.cz>"]

[dependencies]
piston_window = "0.73.0"
piston2d-opengl_graphics = "0.49.0"
rand = "0.3.18"
piston = "0.35.0"
image = "0.17.0"
clap = "2.27.1"